### ISSUE TITLE
How to also add chapter number to the citation?

### ISSUE THREAD

**Issue by albertoZurini** [shafayetShafee/nameref#1]
Is it possible to also have the chapter number (eg. 3.4) together with the title? So from "see Title" to "see 3.4 Title", so as to make it easier for the printed version of the document to be accessible?

**Comment by shafayetShafee** [comment]
Yes, I think it is possible. Need to update the pandoc Lua filter code. I will try to do this as early as possible 😊😀

**Comment by shafayetShafee** [comment]
See the [numbered-nameref](https://github.com/shafayetShafee/nameref#numbered-nameref) and here's the [live demo](https://shafayetshafee.github.io/nameref/numbered_example_html.html).

Let me know if there is anything ambiguous or unclear 😊.
